version: "3"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    container_name: pet-app
    environment:
      SPRING_PROFILES_ACTIVE: local
  db:
    container_name: pet-db
    platform: linux/x86_64
    image: mysql
    environment:
      MYSQL_DATABASE: pet_db
      MYSQL_USER: pet
      MYSQL_PASSWORD: pet
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    ports:
      - "6379:6379"
