version: "3"

services:
  db:
    container_name: pet-db
    platform: linux/arm64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pet_db
      MYSQL_USER: pet
      MYSQL_PASSWORD: pet
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ../db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "18089:8080"
    container_name: pet-app
    restart: always
    command: ./gradlew bootRun
    depends_on:
      - db
      - redis