spring:
  data:
    redis:
      host: redis_boot
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/pet_db
    username: pet
    password: pet
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


jwt:
  header: Authorization
  secret: 4oCYd29uc2Vvay10ZWNoLXNwcmluZy1ib290LWp3dC1zZXJ2aWNlLXNlY3JldC13b25zZW9rLXRlY2gtc3ByaW5nLWJvb3Qtand0LXNlcnZpY2Utc2VjcmV04oCZCg==
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 604800

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    defaultModelsExpandDepth: -1